base_images:
  assisted-image-service:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-image-service
  assisted-installer:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-installer
  assisted-installer-agent:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-installer-agent
  assisted-installer-controller:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-installer-controller
  assisted-service:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-service
  assisted-test-infra:
    name: ocm-2.8
    namespace: edge-infrastructure
    tag: assisted-test-infra
  base:
    name: "4.13"
    namespace: ocp
    tag: base
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  machine-os-content-override:
    name: rhel-coreos-9-oci
    namespace: rhcos-devel
    tag: 412.90.202212061116-0
  ocp_builder_rhel-8-golang-1.18-openshift-4.12:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.18-openshift-4.12
  rhel-coreos-8-extensions-override:
    name: rhel-coreos-9-oci
    namespace: rhcos-devel
    tag: 412.90.202212061116-0-extensions
  rhel-coreos-8-override:
    name: rhel-coreos-9-oci
    namespace: rhcos-devel
    tag: 412.90.202212061116-0
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile.rhel7
  from: base
  inputs:
    ocp_builder_rhel-8-golang-1.18-openshift-4.12:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12
  to: machine-config-operator
promotion:
  disabled: true
  name: "4.13"
  namespace: ocp
releases:
  hosted-ocp-previous:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.12"
  initial:
    integration:
      name: "4.13"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.13"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|OWNERS_ALIASES|LICENSE)$
  steps:
    cluster_profile: aws
    pre:
    - as: test-prestep
      cli: latest
      commands: |
        #!/usr/bin/env bash

        oc registry login

        oc adm release new \
          --from-release="$RELEASE_IMAGE_LATEST" \
          --to-image="registry.ci.openshift.org/$NAMESPACE/release:latest" \
            rhel-coreos-8="quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7e5181599619e8c21e47336f687f94b2af162635fb0a44bcfbb7726560730441" \
            rhel-coreos-8-extensions="quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fcb1dfb2e6b945c3c14a45f619fc3f61e17273b4584559ea55346cf7f0c4657e" \
            machine-os-content="quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1a7280333a4f412e037fa025704646b65c7757f53650c1c3a30e792358058aa1"

        oc adm release info "registry.ci.openshift.org/$NAMESPACE/release:latest"
      from: src
      resources:
        requests:
          cpu: 250m
    - chain: ipi-aws-pre
    workflow: openshift-e2e-aws
- as: e2e-gcp-op
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|OWNERS_ALIASES|LICENSE)$
  steps:
    cluster_profile: gcp
    pre:
    - as: test-prestep
      cli: latest
      commands: |
        #!/usr/bin/env bash

        oc registry login

        oc adm release new \
          --from-release="$RELEASE_IMAGE_LATEST" \
          --to-image="registry.ci.openshift.org/$NAMESPACE/release:latest" \
            rhel-coreos-8="quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7e5181599619e8c21e47336f687f94b2af162635fb0a44bcfbb7726560730441" \
            rhel-coreos-8-extensions="quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fcb1dfb2e6b945c3c14a45f619fc3f61e17273b4584559ea55346cf7f0c4657e" \
            machine-os-content="quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1a7280333a4f412e037fa025704646b65c7757f53650c1c3a30e792358058aa1"

        oc adm release info "registry.ci.openshift.org/$NAMESPACE/release:latest"
      from: src
      resources:
        requests:
          cpu: 250m
    - chain: ipi-gcp-pre
    test:
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-gcp
zz_generated_metadata:
  branch: master
  org: openshift
  repo: machine-config-operator
  variant: rhel-coreos-9
